name = "MatrixProductBP"
uuid = "3d39929c-b583-45fa-b331-3f50b693a38a"
authors = ["stecrotti <stefano.crotti@polito.it>"]
version = "0.7.0"

[deps]
CavityTools = "217fe2f1-7e3d-419f-9934-cd6900c2759a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
IndexedGraphs = "8a731c18-cfb7-4915-927e-cc26b56b67cd"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
Kronecker = "2c470bb0-bcc8-11e8-3dad-c9649493f05e"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
LogarithmicNumbers = "aa2f6b4e-9042-5d33-9679-40d3a6b85899"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
TensorTrains = "89893e69-996d-40b1-ba32-8ff5f34c0dd5"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Unzip = "41fe7b60-77ed-43a1-b4f0-825fd5a5650d"

[compat]
CavityTools = "0.3, 1"
Distributions = "0.25"
IndexedGraphs = "0.5"
InvertedIndices = "1"
Kronecker = "0.5"
Lazy = "0.15"
LinearAlgebra = "1.8"
LogExpFunctions = "0.3"
LogarithmicNumbers = "1"
LoopVectorization = "0.12.157"
Measurements = "2"
ProgressMeter = "1"
Random = "1.8"
Reexport = "1"
SparseArrays = "1.8"
Statistics = "1"
StatsBase = "0.34"
TensorCast = "0.4"
TensorTrains = "0.11"
Tullio = "0.3"
UnPack = "1"
Unzip = "0.2"
julia = "1.8, 1.9, 1.10"
